### ISSUE TITLE
install error 

### ISSUE THREAD

**Issue by nisrine** [zaddach/libqemu-python#1]
Hi,
after the first command I've got this error 
`nisrine@nisrine:~/libqemu-python$ python3 setup.py install
/usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
got version from VCS {'full': '45d13136633cac642333e361b0d70a069c74dd6a', 'version': '0+untagged.g45d1313'}
running build_ext
/usr/bin/python3 build.py
Submodule 'src' (https://github.com/zaddach/libqemu) registered for path 'src'
Cloning into 'src'...
remote: Counting objects: 255174, done.
remote: Total 255174 (delta 0), reused 0 (delta 0), pack-reused 255174
Receiving objects: 100% (255174/255174), 109.63 MiB | 1.21 MiB/s, done.
Resolving deltas: 100% (201678/201678), done.
Checking connectivity... done.
Submodule path 'src': checked out '38ff776ef87e15d5d064c0659d99d1ab1247e3df'

ERROR: "clang" either does not exist or does not work

Traceback (most recent call last):
  File "build.py", line 44, in <module>
    main(parse_args(), os.environ)
  File "build.py", line 32, in main
    subprocess.check_call([configure] + CONFIGURE_PARAMS, cwd = build_dir)
  File "/usr/lib/python3.4/subprocess.py", line 557, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/nisrine/libqemu-python/src/configure', '--target-list=arm-lib,i386-lib,x86_64-lib', '--enable-lib', '--clang=clang', '--cxx=clang++', '--cc=clang', '--with-llvm-config=llvm-config']' returned non-zero exit status 1
error: command '/usr/bin/python3' failed with exit status 1
`
any help?
 thanks

**Comment by nisrine** [comment]
I think it's because in the /usr/bin I have clang-3.5 and not clang should I modify it in the configure file ??

**Comment by zaddach** [comment]
Hi,

I guess you downloaded the zip and I assumed that the git is checked out. try to use the git repository (i.e., git clone git@github.com:zaddach/libqemu-python.git) and then try to build again. I'll need to see how to fix the build in case the project is not cloned from git. Also, yes, your clang-3.5 should be called 'clang'. You can change this in the build script (build.py).

Jonas

**Comment by zaddach** [comment]
Also be careful, for some reason install_requires doesn't work for you. You need llvmlite with the specific version from the setup.py file installed.

**Comment by nisrine** [comment]
Hi Jonas,
I've installed your tool but when I run the test I get this 
`nisrine@nisrine:~/libqemu-python$ python3 -m libqemu.disassemble --arch arm --flag thumb --address 4096 "08 1D"
/usr/bin/python3: Error while finding spec for 'libqemu.disassemble' (<class 'ImportError'>: No module named 'llvmlite')
`
I ve tried to install llvmlite from [here](http://llvmlite.pydata.org/en/latest/install/index.html) using miniconda so I had the version llvmlite-0.9 installed and I coudn't found the version 0.5.1 

can you help

thanks

**Comment by zaddach** [comment]
yes, getting the right version of llvmlite is tricky.
What I did was the following:
git clone https://github.com/numba/llvmlite
( cd llvmlite && git checkout v0.5.1 && python3 setup.py install )

I will update libqemu at some point to work with a more recent LLVM version than 3.5, so that it works with the current llvmlite version. If you find the dependencies of the python binding too cumbersome, also have a look at the files in libqemu-test, these don't need any python. I will also write the same test program to translate single instructions in C at some point.
